runtime: java17
env: standard
# remember to use an instance class compatible with your scaling type
instance_class: F1
handlers:
  - url: .*
    script: auto
service_account: kinetic-abbey-429608-b9@appspot.gserviceaccount.com