runtime: java17
env: standard
entrypoint: 'java -jar target/spring-demo-0.0.1-SNAPSHOT.jar'
instance_class: F1  # Smallest instance for development to minimize costs.

automatic_scaling:  # Use automatic scaling for development to manage instances more flexibly.
  max_instances: 1  # Limit instances to minimize costs.
  min_idle_instances: 0  # Scale down to 0 instances when not in use.
  max_idle_instances: 1  # Limit to 1 to prevent cost from idle instances.
  max_concurrent_requests: 10  # Limit to prevent overuse by too many requests.

handlers:
  - url: .*
    script: auto

# Set environment-specific variables if needed.
env_variables:
  ENV: 'dev'