name: Deploy and Test Workflow

on:
  push:
    branches:
      - master  # Triggers the workflow on push events to dev branch.
  pull_request:
    branches:
      - master # Triggers the workflow on pull request events targeting dev branch.

jobs:
  test:
    # This job runs on pull_request events
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add steps for testing your java app
      - name: Run tests
        run: mvn clean install -DskipTests

  build_and_deploy:
    # This job runs on push events, specifically after PRs are merged into main
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Google Cloud CLI
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run tests
        run: mvn clean install -DskipTests

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          promote: true
          version: 'auto' # Automatically generate a version ID
          deliverables: target/spring-demo-0.0.1-SNAPSHOT.jar # Update this to the path of your built JAR
